apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
spec:
  template:
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/kingdo_puffer/stub-helloworld:latest # Stub image. See https://github.com/vhive-serverless/vhive/issues/68
          ports:
            - name: h2c # For GRPC support
              containerPort: 50051
          env:
            - name: GUEST_PORT # Port on which the firecracker-containerd container is accepting requests
              value: "50051"
            - name: GUEST_IMAGE # Container image to use for firecracker-containerd container
              value: "registry.cn-hangzhou.aliyuncs.com/kingdo_puffer/function-helloworld-python:latest"
